name: apkrestart
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.11
  google_sign_in: ^6.2.2
  dio: ^5.8.0+1
  curved_navigation_bar: ^1.0.6
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Untitled.png
    - assets/searchimages/
    - assets/menscloth/
    - assets/womens/
    - assets/kids/
    - assets/automobiles/
    - assets/sports/
    - assets/home/
    - assets/beauty/
    - assets/toys/
    - assets/cellphones/
    - assets/electronics/
    - assets/comics/
    - assets/flashdeals/
    - assets/brands/
    - assets/topsellers/